CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(300),
    ITEM_NAME VARCHAR(100),
    QTY INT,
    STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );